services:
  strapi:
    platform: linux/amd6
    image: bryanstgarcia/cms-strapi:latest
    container_name: cms-strapi-production
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    # Only add expose when working with reverse proxy. Expose only the container PORT
    expose:
      - "1337"
    #Expose container and host PORT only if not using reverse proxy.
    #ports:
    # - "1337:1337"
    networks:
      - reverse-proxy-network
    restart: always

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    driver: bridge

